name: CI

on: [push]

jobs:
  greetings:
    runs-on: ubuntu-latest
    name: Greet Again 

    steps:
      - id: foo
        uses: gittrainereu/jm-bash-action@main
        with:
          who-to-greet: 'Mona the Octocat'
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
