name: Share data between jobs

on: [push]

jobs:
  is-2nd-lang-changed:
    name: langtest
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        env:
          SUPER_SECRET: ${{ secrets.SECRET_SUPER_SECRET }}
        run: |
          echo "$SUPER_SECRET" 
          echo "foo" > /tmp/myfile 
          cat /tmp/myfile 
          echo "$SUPER_SECRET" >> /tmp/myfile 
          cat /tmp/myfile 
          echo "foo2" >> /tmp/myfile 
          cat /tmp/myfile 
 
