name: 

on:
  push:
    branches:    
      - 'feature/**'
    paths:
      - 'dist/index.html'

jobs:
  translation-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
      - run: |
          ls -la 
          git branch 
          git branch -r
          COUNT=$(git diff --name-only HEAD origin/master -- dist/en/index.html | grep -c "dist/en/index.html")
          if [ $COUNT -eq 0 ] ; then  echo "dist/en/index.html not changed"; exit 1; else "Change in lang detected. Happy"; fi
