name: langchecker

on:
  push:
    branches:    
      - 'feature/**'
    paths:
      - 'dist/index.html'

jobs:
  translation-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
      - run: |
          ls -la 
          git branch 
          git branch -r
          COUNT=$(git diff --name-only HEAD origin/master -- dist/en/index.html | grep -c "dist/en/index.html")
          # This shows the output - need to be seperately 
          if [ $COUNT -eq 0 ] ; then  echo "dist/en/index.html not changed"; else echo "Change in lang detected - Happy"; fi
          # Return exit - code of 1, echo before that in the same line does not work 
          if [ $COUNT -eq 0 ] ; then exit 1; fi
         
